services:
  apisix:
    image: zqzl/apisix-gateway:latest
    container_name: zqzl-apisix-gateway
    ports:
      - "80:9080"
      - "443:9443"
      - "9090:9090"
    depends_on:
      sso-web:
        condition: service_started
      user-web:
        condition: service_started
      sso-server:
        condition: service_started
      user-server:
        condition: service_started
    networks:
      - zqzl-network
    restart: unless-stopped

  user-server:
    image: zqzl/user-server:latest
    container_name: zqzl-user-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - GRPC_SERVER_PORT=9090
      - SSO_GRPC_HOST=sso-server
      - SSO_GRPC_PORT=9090
      - SSO_ISSUER_URI=http://api.bw.com
      - SSO_JWK_SET_URI=http://sso-server:8080/oauth2/jwks
      - SSO_TOKEN_URI=http://api.bw.com/oauth2/token
      - SSO_AUTHORIZATION_URI=http://api.bw.com/oauth2/authorize
      - SSO_REDIRECT_URI=http://admin.bw.com/sso/callback
      - SSO_OAUTH2_SCOPE=openid profile read write
    networks:
      - zqzl-network
    restart: unless-stopped

  sso-server:
    image: zqzl/sso-server:latest
    container_name: zqzl-sso-server
    depends_on:
      user-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - GRPC_SERVER_PORT=9090
      - USER_GRPC_HOST=user-server
      - USER_GRPC_PORT=9090
      - SSO_ISSUER_URI=http://api.bw.com
      - SSO_JWK_SET_URI=http://sso-server:8080/oauth2/jwks
      - SSO_WEB_LOGIN_URL=http://sso.bw.com/login
      - SSO_WEB_LOGOUT_URL=http://sso.bw.com/login?logout
      - SSO_CLIENT_USER_WEB_REDIRECT_URI=http://admin.bw.com/sso/callback
    networks:
      - zqzl-network
    restart: unless-stopped

  sso-web:
    image: zqzl/sso-web:latest
    container_name: zqzl-sso-web
    networks:
      - zqzl-network
    depends_on:
      - sso-server
    restart: unless-stopped

  user-web:
    image: zqzl/user-web:latest
    container_name: zqzl-user-web
    networks:
      - zqzl-network
    depends_on:
      - user-server
    restart: unless-stopped

networks:
  zqzl-network:
    driver: bridge
    name: zqzl-network
