include:
  - path: ./ops/docker/compose/services/network.yml
  - path: ./ops/docker/compose/services/user-server.yml
  - path: ./ops/docker/compose/services/sso-server.yml
  - path: ./ops/docker/compose/services/sso-web.yml
  - path: ./ops/docker/compose/services/user-web.yml
  - path: ./ops/docker/compose/services/apisix.yml
