server:
  port: 8081

grpc:
  server:
    port: 9091
  client:
    sso-server:
      address: static://localhost:9090

sso:
  service:
    url: http://localhost:8080

spring:
  jpa:
    show-sql: true

logging:
  level:
    com.user: DEBUG
    org.hibernate.SQL: DEBUG
