server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:user_prod_db;DB_CLOSE_DELAY=-1}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

logging:
  level:
    root: WARN
    com.zqzl.user: INFO
