server:
  port: 8080

grpc:
  server:
    port: 9090
  client:
    user-server:
      address: static://localhost:9091

user:
  service:
    url: http://localhost:8081

logging:
  level:
    com.sso: DEBUG
