server:
  servlet:
    context-path: /sso
  port: 8080

spring:
  application:
    name: sso-server
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

user:
  service:
    url: http://user-server/user

sso:
  ticket:
    expiration: 86400000
