services:
  sso-server:
    image: ${SSO_SERVER_IMAGE}
    container_name: ${PROJECT_NAME}-sso-server
    environment:
      - SPRING_PROFILES_ACTIVE=${SSO_SERVER_PROFILE}
      - SERVER_PORT=${SSO_SERVER_PORT}
      - GRPC_SERVER_PORT=${SSO_SERVER_GRPC_PORT}
      - USER_GRPC_HOST=${USER_GRPC_HOST}
      - USER_GRPC_PORT=${USER_GRPC_PORT}
      - SSO_ISSUER_URI=${SSO_ISSUER_URI}
      - SSO_JWK_SET_URI=${SSO_JWK_SET_URI}
      - SSO_WEB_LOGIN_URL=${SSO_WEB_LOGIN_URL}
      - SSO_WEB_LOGOUT_URL=${SSO_WEB_LOGOUT_URL}
      - SSO_CLIENT_USER_WEB_REDIRECT_URI=${SSO_CLIENT_USER_WEB_REDIRECT_URI}
    networks:
      - zqzl-network
    restart: unless-stopped
