services:
  user-web:
    image: ${USER_WEB_IMAGE}
    container_name: ${PROJECT_NAME}-user-web
    environment:
      - REACT_APP_SSO_SERVER_URL=${REACT_APP_SSO_SERVER_URL}
      - REACT_APP_API_SERVER_URL=${REACT_APP_API_SERVER_URL}
      - REACT_APP_OAUTH2_AUTH_URI=${REACT_APP_OAUTH2_AUTH_URI}
      - REACT_APP_OAUTH2_CLIENT_ID=${REACT_APP_OAUTH2_CLIENT_ID}
      - REACT_APP_OAUTH2_REDIRECT_URI=${REACT_APP_OAUTH2_REDIRECT_URI}
      - REACT_APP_OAUTH2_SCOPE=${REACT_APP_OAUTH2_SCOPE}
    networks:
      - zqzl-network
    depends_on:
      - user-server
    restart: unless-stopped
