services:
  user-server:
    image: ${USER_SERVER_IMAGE}
    container_name: ${PROJECT_NAME}-user-server
    depends_on:
      sso-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${USER_SERVER_PROFILE}
      - SERVER_PORT=${USER_SERVER_PORT}
      - GRPC_SERVER_PORT=${USER_SERVER_GRPC_PORT}
      - SSO_GRPC_HOST=${SSO_GRPC_HOST}
      - SSO_GRPC_PORT=${SSO_GRPC_PORT}
      - SSO_ISSUER_URI=${USER_SSO_ISSUER_URI}
      - SSO_JWK_SET_URI=${USER_SSO_JWK_SET_URI}
      - SSO_TOKEN_URI=${SSO_TOKEN_URI}
      - SSO_AUTHORIZATION_URI=${SSO_AUTHORIZATION_URI}
      - SSO_REDIRECT_URI=${SSO_REDIRECT_URI}
      - SSO_OAUTH2_SCOPE=${SSO_OAUTH2_SCOPE}
    networks:
      - zqzl-network
    restart: unless-stopped
