routes:
  - id: api-sso-server-route
    uri: /v1/auth/*
    priority: 100
    host: api.bw.com
    plugins:
      proxy-rewrite:
        regex_uri: ["^/v1/auth/(.*)", "/sso/v1/auth/$1"]
    upstream:
      type: roundrobin
      nodes:
        "sso-server:8080": 1

  - id: api-oauth2-route
    uri: /oauth2/*
    priority: 99
    host: api.bw.com
    upstream:
      type: roundrobin
      nodes:
        "sso-server:8080": 1

  - id: api-user-server-route
    uri: /v1/users/*
    priority: 98
    host: api.bw.com
    upstream:
      type: roundrobin
      nodes:
        "user-server:8080": 1

  - id: sso-web-route
    uri: /*
    priority: 50
    host: sso.bw.com
    upstream:
      type: roundrobin
      nodes:
        "sso-web:80": 1

  - id: admin-web-route
    uri: /*
    priority: 49
    host: admin.bw.com
    upstream:
      type: roundrobin
      nodes:
        "user-web:80": 1

#END
